version: 2

jobs:
    build:
        working_directory: ~/work-at-olist/callrecords
        docker:
            - image: circleci/python:3.7.0
        steps:
            - checkout
            - restore_cache:
                      key: deps1-{{ .Branch }}-{{ checksum "callrecords/requirements/test.txt" }}
            - run:
                name: Install requirements
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install -r callrecords/requirements/test.txt
            - run:
                name: Running tests
                command: |
                    . venv/bin/activate
                    py.test callrecords
            - run:
                name: Running Flake8
                command: |
                    . venv/bin/activate
                    flake8 --ignore E501 callrecords
            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "callrecords/requirements/test.txt" }}
                paths:
                    - "venv"

