# Generated by Django 2.1.7 on 2019-03-16 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedfee',
            name='time_total',
        ),
        migrations.RemoveField(
            model_name='minutefee',
            name='time_total',
        ),
    ]
