# Generated by Django 2.1.7 on 2019-03-21 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20190316_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='fixed_fee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bills.FixedFee'),
        ),
    ]
